#!/bin/bash

mkdir -p data/chroma_data/upload/

uv sync
uv run uvicorn src.server.main:app --reload --port 8199 > "logs/backend.log" 2>&1 &
uv run streamlit run src/app.py --browser.gatherUsageStats false > "logs/frontend.log" 2>&1 &

wait
