inputs: assets/demo/formula_detection_pdfs
outputs: data/outputs/formula_detection_pdfs
tasks:
  # formula_detection:
  #   model: formula_detection_yolo
  #   model_config:
  #     img_size: 1280
  #     conf_thres: 0.25
  #     iou_thres: 0.45
  #     model_path: /usr/local/share/models/MFD/YOLO/yolo_v8_ft.pt
  #     visualize: True
  # formula_recognition:
  #   model: formula_recognition_unimernet
  #   model_config:
  #     cfg_path: pdf_extract_kit/configs/unimernet.yaml
  #     model_path: /usr/local/share/models/MFR/UniMERNet
  #     visualize: True
  layout_detection:
    model: layout_detection_yolo
    model_config:
      img_size: 1024
      conf_thres: 0.25
      iou_thres: 0.45
      model_path: /usr/local/share/models/Layout/YOLO/doclayout_yolo_ft.pt
      visualize: True
  # ocr:
  #   model: ocr_ppocr
  #   model_config:
  #     lang: ch
  #     show_log: True
  #     det_model_dir: /usr/local/share/models/OCR/PaddleOCR/det/ch_PP-OCRv4_det
  #     rec_model_dir: /usr/local/share/models/OCR/PaddleOCR/rec/ch_PP-OCRv4_rec
  #     det_db_box_thresh: 0.3